/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DataStoreHeader {
    'temp': string;
  }
  interface DataStoreHeaderAttributes extends StencilHTMLAttributes {
    'temp'?: string;
  }

  interface DataStoreSidebarItem {
    'header': string;
    'tables': any;
  }
  interface DataStoreSidebarItemAttributes extends StencilHTMLAttributes {
    'header'?: string;
    'tables'?: any;
  }

  interface DataStoreSidebar {
    'temp': string;
  }
  interface DataStoreSidebarAttributes extends StencilHTMLAttributes {
    'temp'?: string;
  }

  interface DataStoreTable {
    'temp': string;
  }
  interface DataStoreTableAttributes extends StencilHTMLAttributes {
    'temp'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DataStoreHeader': Components.DataStoreHeader;
    'DataStoreSidebarItem': Components.DataStoreSidebarItem;
    'DataStoreSidebar': Components.DataStoreSidebar;
    'DataStoreTable': Components.DataStoreTable;
  }

  interface StencilIntrinsicElements {
    'data-store-header': Components.DataStoreHeaderAttributes;
    'data-store-sidebar-item': Components.DataStoreSidebarItemAttributes;
    'data-store-sidebar': Components.DataStoreSidebarAttributes;
    'data-store-table': Components.DataStoreTableAttributes;
  }


  interface HTMLDataStoreHeaderElement extends Components.DataStoreHeader, HTMLStencilElement {}
  var HTMLDataStoreHeaderElement: {
    prototype: HTMLDataStoreHeaderElement;
    new (): HTMLDataStoreHeaderElement;
  };

  interface HTMLDataStoreSidebarItemElement extends Components.DataStoreSidebarItem, HTMLStencilElement {}
  var HTMLDataStoreSidebarItemElement: {
    prototype: HTMLDataStoreSidebarItemElement;
    new (): HTMLDataStoreSidebarItemElement;
  };

  interface HTMLDataStoreSidebarElement extends Components.DataStoreSidebar, HTMLStencilElement {}
  var HTMLDataStoreSidebarElement: {
    prototype: HTMLDataStoreSidebarElement;
    new (): HTMLDataStoreSidebarElement;
  };

  interface HTMLDataStoreTableElement extends Components.DataStoreTable, HTMLStencilElement {}
  var HTMLDataStoreTableElement: {
    prototype: HTMLDataStoreTableElement;
    new (): HTMLDataStoreTableElement;
  };

  interface HTMLElementTagNameMap {
    'data-store-header': HTMLDataStoreHeaderElement
    'data-store-sidebar-item': HTMLDataStoreSidebarItemElement
    'data-store-sidebar': HTMLDataStoreSidebarElement
    'data-store-table': HTMLDataStoreTableElement
  }

  interface ElementTagNameMap {
    'data-store-header': HTMLDataStoreHeaderElement;
    'data-store-sidebar-item': HTMLDataStoreSidebarItemElement;
    'data-store-sidebar': HTMLDataStoreSidebarElement;
    'data-store-table': HTMLDataStoreTableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
